// =====================================================
// HTTP STATUS CODE CHEAT SHEET Generated By ChatGPT
// =====================================================

// 2xx Success
// 200 OK            → Request succeeded (GET, PUT, DELETE)
// 201 Created       → Resource successfully created (POST)
// 204 No Content    → Success with no response body (common for DELETE)

// 4xx Client Errors
// 400 Bad Request   → Missing or invalid input (validation errors)
// 401 Unauthorized  → Not authenticated (login required)
// 403 Forbidden     → Authenticated but not allowed
// 404 Not Found     → Resource does not exist
// 409 Conflict      → Duplicate or conflicting data (e.g., unique constraint)

// 5xx Server Errors
// 500 Internal Server Error → Generic server/database failure
// 503 Service Unavailable   → Server temporarily down or overloaded

// =====================================================
// QUICK USAGE GUIDE (for THIS project)
//
// POST   → 201 (or 400 / 500)
// GET    → 200 (or 404 / 500)
// PUT    → 200 (or 400 / 404 / 500)
// DELETE → 200 or 204 (or 404 / 500)
// =====================================================


// Basic setup
const express = require('express')
const cors = require('cors')
const sqlite3 = require('sqlite3').verbose()
const { v4: uuidv4 } = require('uuid') 
require('dotenv').config()

const app = express()
const PORT = 8000

// Middleware stuff
app.use(cors())
app.use(express.json())

//Database connection
const db = new sqlite3.Database('resume.db', (err) => {
    if (err){
        console.error("Db connection error:", err.message)
    } else {
        console.log("Connected to SQLite database")
    }
})

// This a route to test connection
app.get('/ping', (req,res) => {
    res.json({ message: 'Server is alive' })
})

// ===================================================================
// JOB ROUTES BELOW
// ===================================================================

// POST job route
app.post('/api/jobs', (req,res,next) => {
    let strJobID = uuidv4()
    let strTitle = req.body.title ? req.body.title.trim() : ""
    let strCompany = req.body.company ? req.body.company.trim() : ""
    let strStartDate = req.body.startDate ? req.body.startDate.trim() : ""
    let strEndDate = req.body.endDate ? req.body.endDate.trim() : ""
    
    // Lets validate the data
    if(!strJobID || !strTitle || !strCompany || !strStartDate || !strEndDate){
        return res.status(400).json({ message: "All fields are required" })
    }

    const strQuery = `INSERT INTO tblJobs (JobID, Title, Company, StartDate, EndDate) VALUES (?, ?, ?, ?, ?)`

    db.run(strQuery, [strJobID, strTitle, strCompany, strStartDate, strEndDate], function (err){
        if(err){
            console.error("Insert Error:", err.message)
            return res.status(500).json({ message:"Failed to create the job" })
        }

        return res.status(201).json({ 
            message:"Job created successfully!",
            job: {
                JobID: strJobID,
                Title: strTitle,
                Company: strCompany,
                StartDate: strStartDate,
                EndDate: strEndDate
            }
        })
    })
})

// GET ALL of the jobs route
app.get('/api/jobs', (req,res,next) => {
    const strQuery = `SELECT * FROM tblJobs ORDER BY StartDate DESC`

    db.all(strQuery,[],function (err,arrRows) {

        if (err) {
            console.error("Error Fetching:", err.message)
            return res.status(500).json({ message: "Failed to GET all jobs" })
        }

        return res.status(200).json({
            message: "Jobs retrieved successfully",
            jobs: arrRows
        })
    })
})

// PUT to update job using a URL param
app.put('/api/jobs/:id', (req,res,next) => {
    const strJobID = req.params.id
    let strTitle = req.body.title ? req.body.title.trim() : ""
    let strCompany = req.body.company ? req.body.company.trim() : ""
    let strStartDate = req.body.startDate ? req.body.startDate.trim() : ""
    let strEndDate = req.body.endDate ? req.body.endDate.trim() : ""

    if (!strTitle || !strCompany || !strStartDate || !strEndDate) {
        return res.status(400).json({ message: "All fields are required" })
    }

    const strQuery = `UPDATE tblJobs SET Title=?, Company=?, StartDate=?, EndDate=? WHERE JobID=?`

    db.run(strQuery, [strTitle, strCompany, strStartDate, strEndDate, strJobID], function (err) {
        if (err) {
            console.error("Error updating job:", err.message)
            return res.status(500).json({ message: "Failed to update job" })
        }
        if (this.changes === 0) return res.status(404).json({ message: "Job not found" })

        return res.status(200).json({ 
            message: `Job with ID ${strJobID} updated successfully`
        })
    })
})

// DELETE job to, well, delete the job, pretty self explanatory
app.delete('/api/jobs/:id', (req,res,next) => {
    const strJobID = req.params.id

    const strQuery = `DELETE FROM tblJobs WHERE JobID=?`

    db.run(strQuery, [strJobID], function (err) {
        if (err) {
            console.error("Error deleting job:", err.message)
            return res.status(500).json({ message: "Failed to delete job" })
        }
        if (this.changes === 0) return res.status(404).json({ message: "Job not found" })
        return res.status(200).json({ 
            message: `Job with ID ${strJobID} deleted successfully`
        })
    })
})


// ===================================================================
// JOB DETAILS ROUTES BELOW
// ===================================================================

// POST new detail for a job
app.post('/api/jobs/:id/details', (req,res,next) => {
    const strDetailID = uuidv4()
    const strJobID = req.params.id
    const strDetail = req.body.detail ? req.body.detail.trim() : ""

    if (!strDetail) {
        return res.status(400).json({ message: "Detail text is required" })
    }

    const strQuery = `INSERT INTO tblJobDetails (DetailID, JobID, Detail) VALUES (?, ?, ?)`

    db.run(strQuery, [strDetailID, strJobID, strDetail], (err) => {
        if (err) {
            console.error("Error creating detail:", err.message)
            return res.status(500).json({ message: "Failed to create detail" })
        }
        return res.status(201).json({
            message: "Detail created successfully",
            detail: { DetailID: strDetailID, JobID: strJobID, Detail: strDetail }
        })
    })
})


// GET all the details for a job
app.get('/api/jobs/:id/details', (req,res,next) => {
    const strJobID = req.params.id

    const strQuery = `SELECT * FROM tblJobDetails WHERE JobID=?`

    db.all(strQuery, [strJobID], (err, arrRows) => {
        if (err) {
            console.error("Error fetching the job details:", err.message)
            return res.status(500).json({ message: "Failed to get the job details" })
        }
        return res.status(200).json({
            message: "Job details retrieved successfully",
            data: arrRows
        })
    })
})

// DELETE for if you wanna delete a detail
app.delete('/api/details/:id', (req,res,next) => {
    const strDetailID = req.params.id

    const strQuery = `DELETE FROM tblJobDetails WHERE DetailID=?`

    db.run(strQuery, [strDetailID], function (err) {
        if (err) {
            console.error("Error deleting detail:", err.message)
            return res.status(500).json({ message: "Failed to delete detail" })
        }
        if (this.changes === 0) return res.status(404).json({ message: "Detail not found" })
        return res.status(200).json({ message: `Detail with ID ${strDetailID} deleted successfully` })
    })
})

// ===================================================================
// SKILL CATEGORIES ROUTES BELOW
// ===================================================================

// POST new skill category
app.post('/api/skillcategories', (req,res,next) => {
    const strCategoryID = uuidv4()
    const strName = req.body.name ? req.body.name.trim() : ""

    if (!strName) {
        return res.status(400).json({ message: "Category name is required" })
    }

    const strQuery = `INSERT INTO tblSkillCategories (CategoryID, Name) VALUES (?, ?)`

    db.run(strQuery, [strCategoryID, strName], (err) => {
        if (err) {
            console.error("Error creating skill category:", err.message)
            return res.status(500).json({ message: "Failed to create skill category" })
        }
        return res.status(201).json({
            message: "Skill category created successfully",
            category: { CategoryID: strCategoryID, Name: strName }
        })
    })
})

// GET all skill categories
app.get('/api/skillcategories', (req,res,next) => {
    const strQuery = `SELECT * FROM tblSkillCategories ORDER BY Name`

    db.all(strQuery, [], (err, arrRows) => {
        if (err) {
            console.error("Error fetching skill categories:", err.message)
            return res.status(500).json({ message: "Failed to get skill categories" })
        }
        return res.status(200).json({
            message: "Skill categories retreived successfully",
            data: arrRows
        })
    })
})

// DELETE skill category
app.delete('/api/skillcategories/:id', (req,res,next) => {
    const strCategoryID = req.params.id

    const strQuery = `DELETE FROM tblSkillCategories WHERE CategoryID=?`

    db.run(strQuery, [strCategoryID], function (err) {
        if (err) {
            console.error("Error deleting skill category:", err.message)
            return res.status(500).json({ message: "Failed to delete skill category" })
        }
        if (this.changes === 0) return res.status(404).json({ message: "Skill category not found" })
        return res.status(200).json({ message: `Skill category with ID ${strCategoryID} deleted successfully` })
    })
})

// ===================================================================
// SKILLS ROUTES BELOW
// ===================================================================

// POST a new skill
app.post('/api/skills', (req,res,next) => {
    const strSkillID = uuidv4()
    const strCategoryID = req.body.categoryId ? req.body.categoryId.trim() : ""
    const strName = req.body.name ? req.body.name.trim() : ""

    if (!strCategoryID || !strName) {
        return res.status(400).json({ message: "Category ID and skill name are required" })
    }

    const strQuery = `INSERT INTO tblSkills (SkillID, CategoryID, Name) VALUES (?, ?, ?)`

    db.run(strQuery, [strSkillID, strCategoryID, strName], (err) => {
        if (err) {
            console.error("Error creating skill:", err.message)
            return res.status(500).json({ message: "Failed to create skill" })
        }
        return res.status(201).json({
            message: "Skill created successfully",
            skill: { SkillID: strSkillID, CategoryID: strCategoryID, Name: strName }
        })
    })
})

// GET all skills, which can be filtered by category (I think this could be useful on frontend to 
// improve even further if I decide to implement it), even if it makes this query a little quirky,
// This was created with the help of AI (I wrote most of the route and asked it to help me add filtering
// by category)
app.get('/api/skills', (req, res) => {
    const strCategoryID = req.query.categoryId
    let strQuery = `SELECT * FROM tblSkills`
    let arrParams = []

    if (strCategoryID) {
        strQuery += ` WHERE CategoryID=?`
        arrParams.push(strCategoryID)
    }

    db.all(strQuery, arrParams, (err, arrRows) => {
        if (err) {
            console.error("Error fetching skills:", err.message)
            return res.status(500).json({ message: "Failed to get skills" })
        }
        return res.status(200).json({
            message: "Skills retreved successfully",
            data: arrRows
        })
    })
})

// DELETE as kill
app.delete('/api/skills/:id', (req,res,next) => {
    const strSkillID = req.params.id
    const strQuery = `DELETE FROM tblSkills WHERE SkillID=?`

    db.run(strQuery, [strSkillID], function (err) {
        if (err) {
            console.error("Error deleting skill:", err.message)
            return res.status(500).json({ message: "Failed to delete skill" })
        }
        if (this.changes === 0) return res.status(404).json({ message: "Skill not found" })
        return res.status(200).json({ message: `Skill with ID ${strSkillID} deleted successfully` })
    })
})

// ===================================================================
// CERTIFICATIONS ROUTES BELOW
// ===================================================================

// POST new certifications!
app.post('/api/certifications', (req,res,next) => {
    const strCertID = uuidv4()
    const strName = req.body.name ? req.body.name.trim() : ""
    const strIssuer = req.body.issuer ? req.body.issuer.trim() : ""
    const strDateEarned = req.body.dateEarned ? req.body.dateEarned.trim() : ""

    if (!strName || !strIssuer || !strDateEarned) {
        return res.status(400).json({ message: "Name, issuer, and date earned are required" })
    }

    const strQuery = `INSERT INTO tblCertifications (CertID, Name, Issuer, DateEarned) VALUES (?, ?, ?, ?)`

    db.run(strQuery, [strCertID, strName, strIssuer, strDateEarned], (err) => {
        if (err) {
            console.error("Error creating certification:", err.message)
            return res.status(500).json({ message: "Failed to create certification" })
        }
        return res.status(201).json({
            message: "Certification created successfully",
            certification: { CertID: strCertID, Name: strName, Issuer: strIssuer, DateEarned: strDateEarned }
        })
    })
})

// GET all da certifications
app.get('/api/certifications', (req,res,next) => {
    const strQuery = `SELECT * FROM tblCertifications ORDER BY DateEarned DESC`

    db.all(strQuery, [], (err, arrRows) => {
        if (err) {
            console.error("Error fetching certifications:", err.message)
            return res.status(500).json({ message: "Failed to get certifications" })
        }
        return res.status(200).json({
            message: "Certifications retreived successfully",
            data: arrRows
        })
    })
})

// DELETE certification
app.delete('/api/certifications/:id', (req,res,next) => {
    const strCertID = req.params.id
    const strQuery = `DELETE FROM tblCertifications WHERE CertID=?`

    db.run(strQuery, [strCertID], function (err) {
        if (err) {
            console.error("Error deleting certification:", err.message)
            return res.status(500).json({ message: "Failed to delete certification" })
        }
        if (this.changes === 0) return res.status(404).json({ message: "Certification not found" })
        return res.status(200).json({ message: `Certification with ID ${strCertID} deleted successfully` })
    })
})

// ===================================================================
// AWARDS ROUTES BELOW
// ===================================================================

// POST new award
app.post('/api/awards', (req,res,next) => {
    const strAwardID = uuidv4()
    const strName = req.body.name ? req.body.name.trim() : ""
    const strIssuer = req.body.issuer ? req.body.issuer.trim() : ""
    const strDateEarned = req.body.dateEarned ? req.body.dateEarned.trim() : ""
    const strDescription = req.body.description ? req.body.description.trim() : ""

    if (!strName || !strDateEarned) {
        return res.status(400).json({ message: "Name and date earned are required" })
    }

    const strQuery = `INSERT INTO tblAwards (AwardID, Name, Issuer, DateEarned, Description) VALUES (?, ?, ?, ?, ?)`

    db.run(strQuery, [strAwardID, strName, strIssuer, strDateEarned, strDescription], (err) => {
        if (err) {
            console.error("Error creating award:", err.message)
            return res.status(500).json({ message: "Failed to create award" })
        }
        return res.status(201).json({
            message: "Award created successfully",
            award: { AwardID: strAwardID, Name: strName, Issuer: strIssuer, DateEarned: strDateEarned, Description: strDescription }
        })
    })
})

// GET all awards
app.get('/api/awards', (req,res,next) => {
    const strQuery = `SELECT * FROM tblAwards ORDER BY DateEarned DESC`

    db.all(strQuery, [], (err, arrRows) => {
        if (err) {
            console.error("Error fetching awards:", err.message)
            return res.status(500).json({ message: "Failed to get awards" })
        }
        return res.status(200).json({
            message: "Awards retrieved successfully",
            data: arrRows
        })
    })
})

// DELETE award
app.delete('/api/awards/:id', (req,res,next) => {
    const strAwardID = req.params.id

    const strQuery = `DELETE FROM tblAwards WHERE AwardID=?`

    db.run(strQuery, [strAwardID], function (err) {
        if (err) {
            console.error("Error deleting award:", err.message)
            return res.status(500).json({ message: "Failed to delete award" })
        }
        if (this.changes === 0) return res.status(404).json({ message: "Award not found" })
        return res.status(200).json({ message: `Award with ID ${strAwardID} deleted successfully` })
    })
})



// Start server
app.listen(PORT, () => {
    console.log(`Server running on http://localhost:${PORT}`)
})


