// =====================================================
// HTTP STATUS CODE CHEAT SHEET Generated By ChatGPT
// =====================================================

// 2xx Success
// 200 OK            → Request succeeded (GET, PUT, DELETE)
// 201 Created       → Resource successfully created (POST)
// 204 No Content    → Success with no response body (common for DELETE)

// 4xx Client Errors
// 400 Bad Request   → Missing or invalid input (validation errors)
// 401 Unauthorized  → Not authenticated (login required)
// 403 Forbidden     → Authenticated but not allowed
// 404 Not Found     → Resource does not exist
// 409 Conflict      → Duplicate or conflicting data (e.g., unique constraint)

// 5xx Server Errors
// 500 Internal Server Error → Generic server/database failure
// 503 Service Unavailable   → Server temporarily down or overloaded

// =====================================================
// QUICK USAGE GUIDE (for THIS project)
//
// POST   → 201 (or 400 / 500)
// GET    → 200 (or 404 / 500)
// PUT    → 200 (or 400 / 404 / 500)
// DELETE → 200 or 204 (or 404 / 500)
// =====================================================


// Basic setup
const express = require('express')
const cors = require('cors')
const sqlite3 = require('sqlite3').verbose()
const { v4: uuidv4 } = require('uuid') 
const path = require('path')
require('dotenv').config()

const app = express()
const PORT = 8000

// Middleware stuff
app.use(cors())
app.use(express.json())

// Ai used for this
app.use(express.static(path.join(__dirname, '..', 'frontend')))

//Database connection
const db = new sqlite3.Database('resume.db', (err) => {
    if (err){
        console.error("Db connection error:", err.message)
    } else {
        console.log("Connected to SQLite database")
    }
})

// This a route to test connection
app.get('/ping', (req,res) => {
    res.json({ message: 'Server is alive' })
})

// Serve frontend SPA from express
app.get('/', (req,res) => {
    res.sendFile(path.join(__dirname, '..', 'frontend', 'index.html'))
})


// ===================================================================
// PROFILE ROUTES BELOW
// ===================================================================

// POST create profile
app.post('/api/profile', (req,res,next) => {
    const strProfileID = uuidv4()
    const strFullName = req.body.fullName ? req.body.fullName.trim() : ""
    const strEmail = req.body.email ? req.body.email.trim() : ""
    const strPhone = req.body.phone ? req.body.phone.trim() : ""
    const strLocation = req.body.location ? req.body.location.trim() : ""
    const strLinkedIn = req.body.linkedIn ? req.body.linkedIn.trim() : ""
    const strGitHub = req.body.gitHub ? req.body.gitHub.trim() : ""
    const strWebsite = req.body.website ? req.body.website.trim() : ""

    if (!strFullName || !strEmail) {
        return res.status(400).json({ message: "Full name and email are required" })
    }

    const strCheckQuery = `SELECT ProfileID FROM tblProfile LIMIT 1`

    db.get(strCheckQuery, [], (err, objRow) => {
        if (err) {
            console.error("Error checking existing profile:", err.message)
            return res.status(500).json({ message: "Failed to check profile" })
        }

        if (objRow) {
            return res.status(409).json({ message: "Profile already exists. Please edit profile instead." })
        }

        const strInsertQuery = `INSERT INTO tblProfile (ProfileID, FullName, Email, Phone, Location, LinkedIn, GitHub, Website) VALUES (?, ?, ?, ?, ?, ?, ?, ?)`

        db.run(strInsertQuery, [strProfileID, strFullName, strEmail, strPhone, strLocation, strLinkedIn, strGitHub, strWebsite], (err) => {
            if (err) {
                console.error("Error creating profile:", err.message)
                return res.status(500).json({ message: "Failed to create profile" })
            }

            return res.status(201).json({
                message: "Profile created successfully",
                profile: {
                    ProfileID: strProfileID,
                    FullName: strFullName,
                    Email: strEmail,
                    Phone: strPhone,
                    Location: strLocation,
                    LinkedIn: strLinkedIn,
                    GitHub: strGitHub,
                    Website: strWebsite
                }
            })
        })
    })
})

// GET profile
app.get('/api/profile', (req,res,next) => {
    const strQuery = `SELECT * FROM tblProfile LIMIT 1`

    db.get(strQuery, [], (err, objRow) => {
        if (err) {
            console.error("Error getting profile:", err.message)
            return res.status(500).json({ message: "Failed to get profile" })
        }

        if (!objRow) {
            return res.status(404).json({ message: "Profile not found" })
        }

        return res.status(200).json({
            message: "Profile retrieved successfully",
            profile: objRow
        })
    })
})

// PUT update profile
app.put('/api/profile/:id', (req,res,next) => {
    const strProfileID = req.params.id
    const strFullName = req.body.fullName ? req.body.fullName.trim() : ""
    const strEmail = req.body.email ? req.body.email.trim() : ""
    const strPhone = req.body.phone ? req.body.phone.trim() : ""
    const strLocation = req.body.location ? req.body.location.trim() : ""
    const strLinkedIn = req.body.linkedIn ? req.body.linkedIn.trim() : ""
    const strGitHub = req.body.gitHub ? req.body.gitHub.trim() : ""
    const strWebsite = req.body.website ? req.body.website.trim() : ""

    if (!strFullName || !strEmail) {
        return res.status(400).json({ message: "Full name and email are required" })
    }

    const strQuery = `UPDATE tblProfile SET FullName=?, Email=?, Phone=?, Location=?, LinkedIn=?, GitHub=?, Website=? WHERE ProfileID=?`

    db.run(strQuery, [strFullName, strEmail, strPhone, strLocation, strLinkedIn, strGitHub, strWebsite, strProfileID], function (err) {
        if (err) {
            console.error("Error updating profile:", err.message)
            return res.status(500).json({ message: "Failed to update profile" })
        }

        if (this.changes === 0) {
            return res.status(404).json({ message: "Profile not found" })
        }

        return res.status(200).json({
            message: "Profile updated successfully",
            profile: {
                ProfileID: strProfileID,
                FullName: strFullName,
                Email: strEmail,
                Phone: strPhone,
                Location: strLocation,
                LinkedIn: strLinkedIn,
                GitHub: strGitHub,
                Website: strWebsite
            }
        })
    })
})

// ===================================================================
// JOB ROUTES BELOW
// ===================================================================

// POST job route
app.post('/api/jobs', (req,res,next) => {
    let strJobID = uuidv4()
    let strTitle = req.body.title ? req.body.title.trim() : ""
    let strCompany = req.body.company ? req.body.company.trim() : ""
    let strStartDate = req.body.startDate ? req.body.startDate.trim() : ""
    let strEndDate = req.body.endDate ? req.body.endDate.trim() : ""
    let blnIsPresent = req.body.isPresent === true

    if (blnIsPresent) {
        strEndDate = null
    }
    
    // Lets validate the data
    if(!strJobID || !strTitle || !strCompany || !strStartDate || (!strEndDate && !blnIsPresent)){
        return res.status(400).json({ message: "All fields are required" })
    }

    const strQuery = `INSERT INTO tblJobs (JobID, Title, Company, StartDate, EndDate) VALUES (?, ?, ?, ?, ?)`

    db.run(strQuery, [strJobID, strTitle, strCompany, strStartDate, strEndDate], function (err){
        if(err){
            console.error("Insert Error:", err.message)
            return res.status(500).json({ message:"Failed to create the job" })
        }

        return res.status(201).json({ 
            message:"Job created successfully!",
            job: {
                JobID: strJobID,
                Title: strTitle,
                Company: strCompany,
                StartDate: strStartDate,
                EndDate: strEndDate
            }
        })
    })
})

// GET ALL of the jobs route
app.get('/api/jobs', (req,res,next) => {
    const strQuery = `SELECT * FROM tblJobs ORDER BY StartDate DESC`

    db.all(strQuery,[],function (err,arrRows) {

        if (err) {
            console.error("Error Fetching:", err.message)
            return res.status(500).json({ message: "Failed to GET all jobs" })
        }

        return res.status(200).json({
            message: "Jobs retrieved successfully",
            jobs: arrRows
        })
    })
})

// PUT to update job using a URL param
app.put('/api/jobs/:id', (req,res,next) => {
    const strJobID = req.params.id
    let strTitle = req.body.title ? req.body.title.trim() : ""
    let strCompany = req.body.company ? req.body.company.trim() : ""
    let strStartDate = req.body.startDate ? req.body.startDate.trim() : ""
    let strEndDate = req.body.endDate ? req.body.endDate.trim() : ""

    if (!strTitle || !strCompany || !strStartDate || !strEndDate) {
        return res.status(400).json({ message: "All fields are required" })
    }

    const strQuery = `UPDATE tblJobs SET Title=?, Company=?, StartDate=?, EndDate=? WHERE JobID=?`

    db.run(strQuery, [strTitle, strCompany, strStartDate, strEndDate, strJobID], function (err) {
        if (err) {
            console.error("Error updating job:", err.message)
            return res.status(500).json({ message: "Failed to update job" })
        }
        if (this.changes === 0) return res.status(404).json({ message: "Job not found" })

        return res.status(200).json({ 
            message: `Job with ID ${strJobID} updated successfully`
        })
    })
})

// DELETE job to, well, delete the job, pretty self explanatory
app.delete('/api/jobs/:id', (req,res,next) => {
    const strJobID = req.params.id

    const strQuery = `DELETE FROM tblJobs WHERE JobID=?`

    db.run(strQuery, [strJobID], function (err) {
        if (err) {
            console.error("Error deleting job:", err.message)
            return res.status(500).json({ message: "Failed to delete job" })
        }
        if (this.changes === 0) return res.status(404).json({ message: "Job not found" })
        return res.status(200).json({ 
            message: `Job with ID ${strJobID} deleted successfully`
        })
    })
})


// ===================================================================
// JOB DETAILS ROUTES BELOW
// ===================================================================

// POST new detail for a job
app.post('/api/jobs/:id/details', (req,res,next) => {
    const strDetailID = uuidv4()
    const strJobID = req.params.id
    const strDetail = req.body.detail ? req.body.detail.trim() : ""

    if (!strDetail) {
        return res.status(400).json({ message: "Detail text is required" })
    }

    const strQuery = `INSERT INTO tblJobDetails (DetailID, JobID, Detail) VALUES (?, ?, ?)`

    db.run(strQuery, [strDetailID, strJobID, strDetail], (err) => {
        if (err) {
            console.error("Error creating detail:", err.message)
            return res.status(500).json({ message: "Failed to create detail" })
        }
        return res.status(201).json({
            message: "Detail created successfully",
            detail: { DetailID: strDetailID, JobID: strJobID, Detail: strDetail }
        })
    })
})


// GET all the details for a job
app.get('/api/jobs/:id/details', (req,res,next) => {
    const strJobID = req.params.id

    const strQuery = `SELECT * FROM tblJobDetails WHERE JobID=?`

    db.all(strQuery, [strJobID], (err, arrRows) => {
        if (err) {
            console.error("Error fetching the job details:", err.message)
            return res.status(500).json({ message: "Failed to get the job details" })
        }
        return res.status(200).json({
            message: "Job details retrieved successfully",
            data: arrRows
        })
    })
})

// DELETE for if you wanna delete a detail
app.delete('/api/details/:id', (req,res,next) => {
    const strDetailID = req.params.id

    const strQuery = `DELETE FROM tblJobDetails WHERE DetailID=?`

    db.run(strQuery, [strDetailID], function (err) {
        if (err) {
            console.error("Error deleting detail:", err.message)
            return res.status(500).json({ message: "Failed to delete detail" })
        }
        if (this.changes === 0) return res.status(404).json({ message: "Detail not found" })
        return res.status(200).json({ message: `Detail with ID ${strDetailID} deleted successfully` })
    })
})

// ===================================================================
// SKILL CATEGORIES ROUTES BELOW
// ===================================================================

// POST new skill category
app.post('/api/skillcategories', (req,res,next) => {
    const strCategoryID = uuidv4()
    const strName = req.body.name ? req.body.name.trim() : ""

    if (!strName) {
        return res.status(400).json({ message: "Category name is required" })
    }

    const strQuery = `INSERT INTO tblSkillCategories (CategoryID, Name) VALUES (?, ?)`

    db.run(strQuery, [strCategoryID, strName], (err) => {
        if (err) {
            console.error("Error creating skill category:", err.message)
            return res.status(500).json({ message: "Failed to create skill category" })
        }
        return res.status(201).json({
            message: "Skill category created successfully",
            category: { CategoryID: strCategoryID, Name: strName }
        })
    })
})

// GET all skill categories
app.get('/api/skillcategories', (req,res,next) => {
    const strQuery = `SELECT * FROM tblSkillCategories ORDER BY Name`

    db.all(strQuery, [], (err, arrRows) => {
        if (err) {
            console.error("Error fetching skill categories:", err.message)
            return res.status(500).json({ message: "Failed to get skill categories" })
        }
        return res.status(200).json({
            message: "Skill categories retreived successfully",
            data: arrRows
        })
    })
})

// DELETE skill category
app.delete('/api/skillcategories/:id', (req,res,next) => {
    const strCategoryID = req.params.id

    const strQuery = `DELETE FROM tblSkillCategories WHERE CategoryID=?`

    db.run(strQuery, [strCategoryID], function (err) {
        if (err) {
            console.error("Error deleting skill category:", err.message)
            return res.status(500).json({ message: "Failed to delete skill category" })
        }
        if (this.changes === 0) return res.status(404).json({ message: "Skill category not found" })
        return res.status(200).json({ message: `Skill category with ID ${strCategoryID} deleted successfully` })
    })
})

// ===================================================================
// SKILLS ROUTES BELOW
// ===================================================================

// POST a new skill
app.post('/api/skills', (req,res,next) => {
    const strSkillID = uuidv4()
    const strCategoryID = req.body.categoryId ? req.body.categoryId.trim() : ""
    const strName = req.body.name ? req.body.name.trim() : ""

    if (!strCategoryID || !strName) {
        return res.status(400).json({ message: "Category ID and skill name are required" })
    }

    const strQuery = `INSERT INTO tblSkills (SkillID, CategoryID, Name) VALUES (?, ?, ?)`

    db.run(strQuery, [strSkillID, strCategoryID, strName], (err) => {
        if (err) {
            console.error("Error creating skill:", err.message)
            return res.status(500).json({ message: "Failed to create skill" })
        }
        return res.status(201).json({
            message: "Skill created successfully",
            skill: { SkillID: strSkillID, CategoryID: strCategoryID, Name: strName }
        })
    })
})

// GET all skills, which can be filtered by category (I think this could be useful on frontend to 
// improve even further if I decide to implement it), even if it makes this query a little quirky,
// This was created with the help of AI (I wrote most of the route and asked it to help me add filtering
// by category)
app.get('/api/skills', (req,res,next) => {
    const strCategoryID = req.query.categoryId
    let strQuery = `SELECT * FROM tblSkills`
    let arrParams = []

    if (strCategoryID) {
        strQuery += ` WHERE CategoryID=?`
        arrParams.push(strCategoryID)
    }

    db.all(strQuery, arrParams, (err, arrRows) => {
        if (err) {
            console.error("Error fetching skills:", err.message)
            return res.status(500).json({ message: "Failed to get skills" })
        }
        return res.status(200).json({
            message: "Skills retreved successfully",
            data: arrRows
        })
    })
})

// DELETE as kill
app.delete('/api/skills/:id', (req,res,next) => {
    const strSkillID = req.params.id
    const strQuery = `DELETE FROM tblSkills WHERE SkillID=?`

    db.run(strQuery, [strSkillID], function (err) {
        if (err) {
            console.error("Error deleting skill:", err.message)
            return res.status(500).json({ message: "Failed to delete skill" })
        }
        if (this.changes === 0) return res.status(404).json({ message: "Skill not found" })
        return res.status(200).json({ message: `Skill with ID ${strSkillID} deleted successfully` })
    })
})

// ===================================================================
// CERTIFICATIONS ROUTES BELOW
// ===================================================================

// POST new certifications!
app.post('/api/certifications', (req,res,next) => {
    const strCertID = uuidv4()
    const strName = req.body.name ? req.body.name.trim() : ""
    const strIssuer = req.body.issuer ? req.body.issuer.trim() : ""
    const strDateEarned = req.body.dateEarned ? req.body.dateEarned.trim() : ""

    if (!strName || !strIssuer || !strDateEarned) {
        return res.status(400).json({ message: "Name, issuer, and date earned are required" })
    }

    const strQuery = `INSERT INTO tblCertifications (CertID, Name, Issuer, DateEarned) VALUES (?, ?, ?, ?)`

    db.run(strQuery, [strCertID, strName, strIssuer, strDateEarned], (err) => {
        if (err) {
            console.error("Error creating certification:", err.message)
            return res.status(500).json({ message: "Failed to create certification" })
        }
        return res.status(201).json({
            message: "Certification created successfully",
            certification: { CertID: strCertID, Name: strName, Issuer: strIssuer, DateEarned: strDateEarned }
        })
    })
})

// GET all da certifications
app.get('/api/certifications', (req,res,next) => {
    const strQuery = `SELECT * FROM tblCertifications ORDER BY DateEarned DESC`

    db.all(strQuery, [], (err, arrRows) => {
        if (err) {
            console.error("Error fetching certifications:", err.message)
            return res.status(500).json({ message: "Failed to get certifications" })
        }
        return res.status(200).json({
            message: "Certifications retreived successfully",
            data: arrRows
        })
    })
})

// DELETE certification
app.delete('/api/certifications/:id', (req,res,next) => {
    const strCertID = req.params.id
    const strQuery = `DELETE FROM tblCertifications WHERE CertID=?`

    db.run(strQuery, [strCertID], function (err) {
        if (err) {
            console.error("Error deleting certification:", err.message)
            return res.status(500).json({ message: "Failed to delete certification" })
        }
        if (this.changes === 0) return res.status(404).json({ message: "Certification not found" })
        return res.status(200).json({ message: `Certification with ID ${strCertID} deleted successfully` })
    })
})

// ===================================================================
// AWARDS ROUTES BELOW
// ===================================================================

// POST new award
app.post('/api/awards', (req,res,next) => {
    const strAwardID = uuidv4()
    const strName = req.body.name ? req.body.name.trim() : ""
    const strIssuer = req.body.issuer ? req.body.issuer.trim() : ""
    const strDateEarned = req.body.dateEarned ? req.body.dateEarned.trim() : ""
    const strDescription = req.body.description ? req.body.description.trim() : ""

    if (!strName || !strDateEarned) {
        return res.status(400).json({ message: "Name and date earned are required" })
    }

    const strQuery = `INSERT INTO tblAwards (AwardID, Name, Issuer, DateEarned, Description) VALUES (?, ?, ?, ?, ?)`

    db.run(strQuery, [strAwardID, strName, strIssuer, strDateEarned, strDescription], (err) => {
        if (err) {
            console.error("Error creating award:", err.message)
            return res.status(500).json({ message: "Failed to create award" })
        }
        return res.status(201).json({
            message: "Award created successfully",
            award: { AwardID: strAwardID, Name: strName, Issuer: strIssuer, DateEarned: strDateEarned, Description: strDescription }
        })
    })
})

// GET all awards
app.get('/api/awards', (req,res,next) => {
    const strQuery = `SELECT * FROM tblAwards ORDER BY DateEarned DESC`

    db.all(strQuery, [], (err, arrRows) => {
        if (err) {
            console.error("Error fetching awards:", err.message)
            return res.status(500).json({ message: "Failed to get awards" })
        }
        return res.status(200).json({
            message: "Awards retrieved successfully",
            data: arrRows
        })
    })
})

// DELETE award
app.delete('/api/awards/:id', (req,res,next) => {
    const strAwardID = req.params.id

    const strQuery = `DELETE FROM tblAwards WHERE AwardID=?`

    db.run(strQuery, [strAwardID], function (err) {
        if (err) {
            console.error("Error deleting award:", err.message)
            return res.status(500).json({ message: "Failed to delete award" })
        }
        if (this.changes === 0) return res.status(404).json({ message: "Award not found" })
        return res.status(200).json({ message: `Award with ID ${strAwardID} deleted successfully` })
    })
})

// ===================================================================
// AI ROUTES BELOW
// ===================================================================

// AI assisted: helper used to call Gemini with a user key first, then env fallback key.
const callGemini = async (objOptions) => {
    const strUserApiKey = objOptions.strUserApiKey ? objOptions.strUserApiKey.trim() : ""
    const strApiKey = strUserApiKey || (process.env.GEMINI_API_KEY ? process.env.GEMINI_API_KEY.trim() : "")

    if (!strApiKey) {
        return {
            blnSuccess: false,
            intStatus: 400,
            strErrorCode: "MISSING_API_KEY",
            strMessage: "Gemini API key is required. Save a key in Profile or set GEMINI_API_KEY in backend/.env."
        }
    }

    const strModel = "gemini-2.5-flash"

    const strURL = `https://generativelanguage.googleapis.com/v1beta/models/${strModel}:generateContent`

    console.log('Using API key:', strApiKey.substring(0, 8) + '...')
    console.log('Model:', strModel)
    console.log('URL:', strURL)

    const objResponse = await fetch(strURL, {
        method: "POST",
        headers: {
            "Content-Type": "application/json",
            "x-goog-api-key": strApiKey
        },
        body: JSON.stringify({
            generationConfig: {
                temperature: 0.2
            },
            contents: [
                {
                    role: "user",
                    parts: [{ text: objOptions.strPrompt }]
                }
            ]
        })
    })

    const objPayload = await objResponse.json()

    console.log("=== GEMINI RESPONSE ===")
    console.log("Status:", objResponse.status)
    console.log("Body:", JSON.stringify(objPayload, null, 2))

    if (!objResponse.ok) {
        return {
            blnSuccess: false,
            intStatus: objResponse.status,
            strErrorCode: "GEMINI_REQUEST_FAILED",
            strMessage: objPayload.error && objPayload.error.message ? objPayload.error.message : "Gemini request failed."
        }
    }

    const strRawText = objPayload?.candidates?.[0]?.content?.parts?.[0]?.text || ""
    if (!strRawText) {
        return {
            blnSuccess: false,
            intStatus: 502,
            strErrorCode: "EMPTY_AI_RESPONSE",
            strMessage: "Gemini returned an empty response."
        }
    }

    // AI assisted: Gemini may return JSON inside markdown code fences, so strip wrappers before parsing.
    let strJsonText = strRawText.trim()
    const arrCodeFenceMatch = strJsonText.match(/^```(?:json)?\s*([\s\S]*?)\s*```$/i)
    if (arrCodeFenceMatch && arrCodeFenceMatch[1]) {
        strJsonText = arrCodeFenceMatch[1].trim()
    }
    
    if (objOptions.blnRawText) {
        return { blnSuccess: true, intStatus: 200, strText: strRawText }
    }

    let objData = null
    try {
        objData = JSON.parse(strJsonText)
    } catch (err) {
        return {
            blnSuccess: false,
            intStatus: 502,
            strErrorCode: "INVALID_AI_RESPONSE",
            strMessage: "Gemini returned invalid JSON."
        }
    }

    return {
        blnSuccess: true,
        intStatus: 200,
        objData: objData
    }
}

app.get('/api/ai/config', (req,res,next) => {
    return res.status(200).json({
        message: "AI config retrieved successfully",
        data: {
            hasEnvKey: !!(process.env.GEMINI_API_KEY && process.env.GEMINI_API_KEY.trim())
        }
    })
})

// AI assisted: first Gemini endpoint for polishing existing bullet details.
app.post('/api/ai/improve-bullet', async (req,res,next) => {
    const strDetail = req.body.detail ? req.body.detail.trim() : ""
    const strJobTitle = req.body.jobTitle ? req.body.jobTitle.trim() : ""
    const strCompany = req.body.company ? req.body.company.trim() : ""
    const strGeminiApiKey = req.body.geminiApiKey ? req.body.geminiApiKey.trim() : ""

    if (!strDetail) {
        return res.status(400).json({
            message: "Detail is required.",
            error: { code: "VALIDATION_ERROR" }
        })
    }

    const strPrompt = `
You are improving one resume bullet.
Rules:
1) Do not fabricate achievements, numbers, technologies, or responsibilities.
2) Keep claims grounded only in the provided text.
3) Preserve the original meaning.
4) Keep output concise and resume-ready.
5) Return ONLY JSON with shape: {"improvedBullet":"...","reasoning":"..."}.

Input bullet: "${strDetail}"
Job title context: "${strJobTitle}"
Company context: "${strCompany}"
`

    try {
        const objAiResult = await callGemini({
            strUserApiKey: strGeminiApiKey,
            strPrompt: strPrompt
        })

        if (!objAiResult.blnSuccess) {
            return res.status(objAiResult.intStatus).json({
                message: objAiResult.strMessage,
                error: { code: objAiResult.strErrorCode }
            })
        }

        const strImprovedBullet = objAiResult.objData.improvedBullet ? objAiResult.objData.improvedBullet.trim() : ""

        if (!strImprovedBullet) {
            return res.status(502).json({
                message: "AI response did not include an improved bullet.",
                error: { code: "INVALID_AI_RESPONSE" }
            })
        }

        return res.status(200).json({
            message: "Bullet improved successfully",
            data: {
                originalBullet: strDetail,
                improvedBullet: strImprovedBullet,
                reasoning: objAiResult.objData.reasoning ? objAiResult.objData.reasoning : ""
            }
        })
    } catch (err) {
        console.error("Error improving bullet with AI:", err.message)
        return res.status(500).json({
            message: "Unexpected AI server error.",
            error: { code: "AI_SERVER_ERROR" }
        })
    }
})


// AI assisted: builds a detailed prompt from resume data and user preferences, sends to Gemini
app.post('/api/ai/cover-letter', async (req,res,next) => {
    const {
        geminiApiKey, company, role, jobDescription, tone,
        targetLength, paragraphCount, includeAchievements,
        companyContext, profile, jobs, skills, certifications, awards
    } = req.body

    if (!company || !role || !jobDescription) {
        return res.status(400).json({ message: 'Company, role, and job description are required.' })
    }

    let strApplicantName = profile && profile.FullName ? profile.FullName : 'the applicant'

    let strContext = ''

    if (jobs && jobs.length) {
        strContext += '\nWork Experience:\n'
        jobs.forEach((objJob) => {
            strContext += `- ${objJob.title} at ${objJob.company} (${objJob.dates})\n`
            if (objJob.bullets && objJob.bullets.length) {
                objJob.bullets.forEach((strBullet) => {
                    strContext += `  • ${strBullet}\n`
                })
            }
        })
    }

    if (skills && skills.length) {
        strContext += `\nKey Skills: ${skills.join(', ')}\n`
    }

    if (certifications && certifications.length) {
        strContext += `\nCertifications: ${certifications.join(', ')}\n`
    }

    if (awards && awards.length) {
        strContext += '\nAwards & Achievements:\n'
        awards.forEach((strAward) => {
            strContext += `- ${strAward}\n`
        })
    }

    console.log('cover letter payload received:')
    console.log('jobs:', JSON.stringify(jobs, null, 2))
    console.log('skills:', skills)

    const strPrompt = `
Write a cover letter for ${strApplicantName} applying to the role of ${role} at ${company}.

Tone: ${tone}
Target length: approximately ${targetLength} words
Number of body paragraphs: ${paragraphCount}
${includeAchievements ? 'Emphasize specific achievements and quantifiable results where possible.' : ''}
${companyContext ? `Company context: ${companyContext}` : ''}

Job Description:
${jobDescription}

Applicant background:
${strContext}

Write only the body of the cover letter — no subject line, no date, no address block.
Start directly with the opening paragraph. Do not include any preamble or explanation.
`.trim()

    try {
        const objAiResult = await callGemini({
            strUserApiKey: geminiApiKey,
            strPrompt: strPrompt,
            blnRawText: true
        })

        if (!objAiResult.blnSuccess) {
            return res.status(objAiResult.intStatus).json({ message: objAiResult.strMessage })
        }

        return res.status(200).json({ message: 'Cover letter generated.', data: { coverLetter: objAiResult.strText } })
    } catch (objError) {
        console.error('Cover letter Gemini error:', objError.message)
        return res.status(500).json({ message: 'Failed to generate cover letter.', error: objError.message })
    }
})

// Start server
app.listen(PORT, () => {
    console.log(`Server running on http://localhost:${PORT}`)
})

