// =====================================================
// HTTP STATUS CODE CHEAT SHEET Generated By ChatGPT
// =====================================================

// 2xx Success
// 200 OK            → Request succeeded (GET, PUT, DELETE)
// 201 Created       → Resource successfully created (POST)
// 204 No Content    → Success with no response body (common for DELETE)

// 4xx Client Errors
// 400 Bad Request   → Missing or invalid input (validation errors)
// 401 Unauthorized  → Not authenticated (login required)
// 403 Forbidden     → Authenticated but not allowed
// 404 Not Found     → Resource does not exist
// 409 Conflict      → Duplicate or conflicting data (e.g., unique constraint)

// 5xx Server Errors
// 500 Internal Server Error → Generic server/database failure
// 503 Service Unavailable   → Server temporarily down or overloaded

// =====================================================
// QUICK USAGE GUIDE (for THIS project)
//
// POST   → 201 (or 400 / 500)
// GET    → 200 (or 404 / 500)
// PUT    → 200 (or 400 / 404 / 500)
// DELETE → 200 or 204 (or 404 / 500)
// =====================================================


// Basic setup
const express = require('express')
const cors = require('cors')
const { v4: uuidv4 } = require('uuid') 
const path = require('path')
require('dotenv').config()

const db = require('./utils/db')
const { objFieldMaxLengths, sendSuccess, sendError, safeTrim, isValidLength } = require('./utils/responses')

const app = express()
const PORT = 8000


// Middleware stuff
app.use(cors())
app.use(express.json())

// Ai used for this
app.use(express.static(path.join(__dirname, '..', 'frontend')))

// This a route to test connection
app.get('/ping', (req,res) => {
    return sendSuccess(res, 200, 'Server is alive', {})
})

// Serve frontend SPA from express
app.get('/', (req,res) => {
    res.sendFile(path.join(__dirname, '..', 'frontend', 'index.html'))
})


// ===================================================================
// PROFILE ROUTES BELOW
// ===================================================================

app.use('/api/profile', require('./routes/profile'))

// ===================================================================
// JOB ROUTES
// ===================================================================
app.use('/api/jobs', require('./routes/jobs'))
app.use('/api/details', require('./routes/details'))

// ===================================================================
// PROJECT ROUTES
// ===================================================================
app.use('/api/projects', require('./routes/projects'))
app.use('/api/projectdetails', require('./routes/projectdetails'))

// ===================================================================
// SKILL CATEGORIES ROUTES BELOW
// ===================================================================

app.use('/api/skillcategories', require('./routes/skillcategories'))

// ===================================================================
// SKILLS ROUTES BELOW
// ===================================================================

app.use('/api/skills', require('./routes/skills'))

// ===================================================================
// CERTIFICATIONS ROUTES BELOW
// ===================================================================

app.use('/api/certifications', require('./routes/certifications'))

// ===================================================================
// AWARDS ROUTES BELOW
// ===================================================================

app.use('/api/awards', require('./routes/awards'))

// ===================================================================
// SUMMARY ROUTES BELOW
// ===================================================================

app.use('/api/summary', require('./routes/summary'))

// ===================================================================
// EDUCATION ROUTES BELOW
// ===================================================================

app.use('/api/education', require('./routes/education'))

// ===================================================================
// AI ROUTES BELOW
// ===================================================================

app.use('/api/ai', require('./routes/ai'))


// Start server
app.listen(PORT, () => {
    console.log(`Server running on http://localhost:${PORT}`)
})

